
#ifndef UNIFYING_ERROR_H
#define UNIFYING_ERROR_H

enum unifying_error {
    UNIFYING_SUCCESS = 0,
    UNIFYING_ERROR,
    UNIFYING_ID_ERROR,
    UNIFYING_STEP_ERROR,
    UNIFYING_NAME_LENGTH_ERROR,
    UNIFYING_SET_ADDRESS_ERROR,
    UNIFYING_SET_CHANNEL_ERROR,
    UNIFYING_TRANSMIT_ERROR,
    UNIFYING_RECEIVE_ERROR,
    UNIFYING_CHECKSUM_ERROR,
    UNIFYING_PAIR_ERROR,
    UNIFYING_PAIR_ID_ERROR,
    UNIFYING_ENCRYPTION_ERROR,
    UNIFYING_BUFFER_ERROR,
    UNIFYING_BUFFER_FULL_ERROR,
    UNIFYING_BUFFER_EMPTY_ERROR,
    UNIFYING_ERROR_COUNT
};

extern const char* unifying_error_name[UNIFYING_ERROR_COUNT];

#endif
